#!/usr/bin/env python3
"""
Post each developer's daily brief as a comment on their own GitHub issue.

One long-lived issue per stream, one comment per working day. GitHub emails the
@-mentioned owner, so nobody has to remember to open a file, and the thread
becomes the running record of what each person was asked to do and when.

    python3 tools/plan/notify.py --dry-run     # print, send nothing
    python3 tools/plan/notify.py               # post today's briefs

Auth: `GITHUB_TOKEN` in the environment, or a token in
`~/.config/edutrack/gh-token` (mode 600). The token is never printed or
committed.
"""
import argparse
import datetime as dt
import json
import os
import re
import sys
import urllib.error
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import planconfig  # noqa: E402

CFG = planconfig.load()
ROOT = CFG.root
REPO = CFG.repo
API = "https://api.github.com"
MARKER = "<!-- plan-tracker-daily-brief -->"
PLANREL = os.path.relpath(CFG.plan_dir, CFG.root)


def token():
    t = os.environ.get("GITHUB_TOKEN")
    if t:
        return t.strip()
    for path in ("~/.config/plan-tracker/gh-token", "~/.config/edutrack/gh-token"):
        p = os.path.expanduser(path)
        if os.path.exists(p):
            return open(p).read().strip()
    sys.exit("No GitHub token. Set GITHUB_TOKEN, or write one to "
             "~/.config/plan-tracker/gh-token (chmod 600).")


def api(method, path, body=None, tok=None):
    req = urllib.request.Request(
        API + path, method=method,
        data=json.dumps(body).encode() if body is not None else None,
        headers={"Authorization": "Bearer " + tok,
                 "Accept": "application/vnd.github+json",
                 "Content-Type": "application/json",
                 "User-Agent": "edutrack-plan"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read() or "{}")
    except urllib.error.HTTPError as e:
        sys.exit("GitHub %s %s → %s %s" % (method, path, e.code, e.read()[:300].decode()))


def split_brief(text):
    """Split the generated standup file into one chunk per stream."""
    out = {}
    for m in re.finditer(r"^## Stream (\\S+) —.*?(?=^## Stream \\S+ —|\\Z)",
                         text, re.M | re.S):
        out[m.group(1)] = m.group(0).rstrip().rstrip("-").rstrip()
    return out


def find_issue(tok, title):
    for state in ("open", "closed"):
        page = 1
        while True:
            got = api("GET", "/repos/%s/issues?state=%s&per_page=100&page=%d"
                      % (REPO, state, page), tok=tok)
            if not got:
                break
            for i in got:
                if i.get("title") == title and "pull_request" not in i:
                    return i
            page += 1
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--date", default=str(dt.date.today()))
    args = ap.parse_args()

    path = CFG.path("standup", "%s.md" % args.date)
    if not os.path.exists(path):
        sys.exit("No brief for %s — run `plan refresh` first" % args.date)
    briefs = split_brief(open(path, encoding="utf-8").read())
    day = dt.date.fromisoformat(args.date).strftime("%A %d %B %Y")
    tok = None if args.dry_run else token()

    for s, meta in CFG.streams.items():
        name, handle, area = meta["owner"], meta["github"], meta["title"]
        if s not in briefs:
            continue
        if not handle:
            print("  stream %s has no github handle — skipped" % s)
            continue
        title = "%s · daily brief — Stream %s · %s" % (CFG.project, s, name)
        body = (
            "@%s — **%s**\n\n%s\n\n---\n" % (handle, day, briefs[s]) +
            "Full chart: [`%s/GANTT.md`](../blob/%s/%s/GANTT.md) · "
            "interactive: [`%s/gantt.html`](../blob/%s/%s/gantt.html)\n\n" % (
                PLANREL, CFG.branch, PLANREL, PLANREL, CFG.branch, PLANREL) +
            "*Posted automatically at 09:00. Status comes from git — put the task ID "
            "in your commit subject (`feat(scope): %s-001 what you did`) and " % s +
            "this updates itself. If something here is wrong, reply and it gets "
            "fixed in `%s/tasks.csv`.*\n%s" % (PLANREL, MARKER))

        if args.dry_run:
            print("─" * 72)
            print("ISSUE: %s" % title)
            print(body)
            continue

        issue = find_issue(tok, title)
        if not issue:
            issue = api("POST", "/repos/%s/issues" % REPO, {
                "title": title,
                "body": "Rolling daily brief for **Stream %s — %s** (%s) on "
                        "**%s**.\n\nOne comment per working day, generated by "
                        "plan-tracker. Reply here if a task, estimate or dependency "
                        "is wrong.\n%s" % (s, area, name, CFG.project, MARKER),
                "assignees": [handle],
            }, tok=tok)
            print("created issue #%d — %s" % (issue["number"], title))
        api("POST", "/repos/%s/issues/%d/comments" % (REPO, issue["number"]),
            {"body": body}, tok=tok)
        print("posted brief to #%d (%s)" % (issue["number"], name))


if __name__ == "__main__":
    main()
